/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0
*/

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// AdditionalMatch is AND'd onto the policy generated by the host HTTPRoute rule.
// Used to express vngcloud-specific match types not yet covered by core HTTPRoute matches.
type AdditionalMatch struct {
	// Type of match.
	// +kubebuilder:validation:Enum=Header;QueryParam;Method;SourceIP
	// +required
	Type string `json:"type"`

	// Name is the header / query-parameter name. Unused for Method / SourceIP.
	// +optional
	Name *string `json:"name,omitempty"`

	// Compare values: EQUAL_TO | STARTS_WITH | ENDS_WITH | CONTAINS | REGEX (vngcloud-defined).
	// +required
	Compare string `json:"compare"`

	// Value to compare against.
	// +required
	Value string `json:"value"`
}

// FixedResponseAction returns a static response without forwarding the request.
type FixedResponseAction struct {
	// StatusCode of the synthesized response.
	// +required
	StatusCode int32 `json:"statusCode"`

	// ContentType of the response body. Defaults to text/plain when Body is set.
	// +optional
	ContentType *string `json:"contentType,omitempty"`

	// Body of the response.
	// +optional
	Body *string `json:"body,omitempty"`
}

// RedirectAction sends a 3xx response.
type RedirectAction struct {
	// URL to redirect to.
	// +required
	URL string `json:"url"`

	// HTTPCode is the redirect status code (default 302).
	// +optional
	HTTPCode *int32 `json:"httpCode,omitempty"`

	// KeepQueryString preserves the original query string in the redirect.
	// +optional
	KeepQueryString *bool `json:"keepQueryString,omitempty"`
}

// RuleAction overrides the default REDIRECT_TO_POOL action of the host rule.
type RuleAction struct {
	// Type of action.
	// +kubebuilder:validation:Enum=FixedResponse;Reject;Redirect
	// +required
	Type string `json:"type"`

	// FixedResponse is required when Type is "FixedResponse".
	// +optional
	FixedResponse *FixedResponseAction `json:"fixedResponse,omitempty"`

	// Redirect is required when Type is "Redirect".
	// +optional
	Redirect *RedirectAction `json:"redirect,omitempty"`
}

// ListenerRuleConfigSpec defines the desired state of ListenerRuleConfig.
type ListenerRuleConfigSpec struct {
	// AdditionalMatches are AND'd with the host HTTPRoute rule's standard matches.
	// +optional
	AdditionalMatches []AdditionalMatch `json:"additionalMatches,omitempty"`

	// Actions, if set, supersede the host rule's default REDIRECT_TO_POOL action.
	// +optional
	Actions []RuleAction `json:"actions,omitempty"`

	// Position pins policy ordering within the listener. Default is controller-assigned
	// per Gateway-API match-specificity rules.
	// +optional
	Position *int32 `json:"position,omitempty"`
}

// ListenerRuleConfigStatus defines the observed state of ListenerRuleConfig.
type ListenerRuleConfigStatus struct {
	// +optional
	Conditions []metav1.Condition `json:"conditions,omitempty"`
	// +optional
	ObservedGeneration int64 `json:"observedGeneration,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:shortName=lrc

// ListenerRuleConfig is the Schema for the listenerruleconfigs API.
type ListenerRuleConfig struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   ListenerRuleConfigSpec   `json:"spec,omitempty"`
	Status ListenerRuleConfigStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ListenerRuleConfigList contains a list of ListenerRuleConfig.
type ListenerRuleConfigList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ListenerRuleConfig `json:"items"`
}

func init() {
	SchemeBuilder.Register(&ListenerRuleConfig{}, &ListenerRuleConfigList{})
}
