//go:build !ignore_autogenerated

/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	"sigs.k8s.io/gateway-api/apis/v1alpha2"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommonPolicyStatus) DeepCopyInto(out *CommonPolicyStatus) {
	*out = *in
	if in.Ancestors != nil {
		in, out := &in.Ancestors, &out.Ancestors
		*out = make([]v1alpha2.PolicyAncestorStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommonPolicyStatus.
func (in *CommonPolicyStatus) DeepCopy() *CommonPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(CommonPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommonStatus) DeepCopyInto(out *CommonStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommonStatus.
func (in *CommonStatus) DeepCopy() *CommonStatus {
	if in == nil {
		return nil
	}
	out := new(CommonStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VKSBackendPolicy) DeepCopyInto(out *VKSBackendPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VKSBackendPolicy.
func (in *VKSBackendPolicy) DeepCopy() *VKSBackendPolicy {
	if in == nil {
		return nil
	}
	out := new(VKSBackendPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VKSBackendPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VKSBackendPolicyList) DeepCopyInto(out *VKSBackendPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VKSBackendPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VKSBackendPolicyList.
func (in *VKSBackendPolicyList) DeepCopy() *VKSBackendPolicyList {
	if in == nil {
		return nil
	}
	out := new(VKSBackendPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VKSBackendPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VKSBackendPolicySpec) DeepCopyInto(out *VKSBackendPolicySpec) {
	*out = *in
	if in.TargetRefs != nil {
		in, out := &in.TargetRefs, &out.TargetRefs
		*out = make([]v1alpha2.LocalPolicyTargetReference, len(*in))
		copy(*out, *in)
	}
	if in.TargetType != nil {
		in, out := &in.TargetType, &out.TargetType
		*out = new(string)
		**out = **in
	}
	if in.PoolAlgorithm != nil {
		in, out := &in.PoolAlgorithm, &out.PoolAlgorithm
		*out = new(string)
		**out = **in
	}
	if in.Stickiness != nil {
		in, out := &in.Stickiness, &out.Stickiness
		*out = new(bool)
		**out = **in
	}
	if in.EnableTLSEncryption != nil {
		in, out := &in.EnableTLSEncryption, &out.EnableTLSEncryption
		*out = new(bool)
		**out = **in
	}
	if in.TargetNodeLabels != nil {
		in, out := &in.TargetNodeLabels, &out.TargetNodeLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ManageDFPMembers != nil {
		in, out := &in.ManageDFPMembers, &out.ManageDFPMembers
		*out = new(bool)
		**out = **in
	}
	if in.ProxyProtocol != nil {
		in, out := &in.ProxyProtocol, &out.ProxyProtocol
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VKSBackendPolicySpec.
func (in *VKSBackendPolicySpec) DeepCopy() *VKSBackendPolicySpec {
	if in == nil {
		return nil
	}
	out := new(VKSBackendPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VKSBackendPolicyStatus) DeepCopyInto(out *VKSBackendPolicyStatus) {
	*out = *in
	in.CommonStatus.DeepCopyInto(&out.CommonStatus)
	in.CommonPolicyStatus.DeepCopyInto(&out.CommonPolicyStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VKSBackendPolicyStatus.
func (in *VKSBackendPolicyStatus) DeepCopy() *VKSBackendPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(VKSBackendPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VKSGatewayPolicy) DeepCopyInto(out *VKSGatewayPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VKSGatewayPolicy.
func (in *VKSGatewayPolicy) DeepCopy() *VKSGatewayPolicy {
	if in == nil {
		return nil
	}
	out := new(VKSGatewayPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VKSGatewayPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VKSGatewayPolicyList) DeepCopyInto(out *VKSGatewayPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VKSGatewayPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VKSGatewayPolicyList.
func (in *VKSGatewayPolicyList) DeepCopy() *VKSGatewayPolicyList {
	if in == nil {
		return nil
	}
	out := new(VKSGatewayPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VKSGatewayPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VKSGatewayPolicySpec) DeepCopyInto(out *VKSGatewayPolicySpec) {
	*out = *in
	if in.TargetRefs != nil {
		in, out := &in.TargetRefs, &out.TargetRefs
		*out = make([]v1alpha2.LocalPolicyTargetReferenceWithSectionName, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AllowedCIDRs != nil {
		in, out := &in.AllowedCIDRs, &out.AllowedCIDRs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.InsertHeaders != nil {
		in, out := &in.InsertHeaders, &out.InsertHeaders
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.TimeoutClient != nil {
		in, out := &in.TimeoutClient, &out.TimeoutClient
		*out = new(v1.Duration)
		**out = **in
	}
	if in.TimeoutMember != nil {
		in, out := &in.TimeoutMember, &out.TimeoutMember
		*out = new(v1.Duration)
		**out = **in
	}
	if in.TimeoutConnection != nil {
		in, out := &in.TimeoutConnection, &out.TimeoutConnection
		*out = new(v1.Duration)
		**out = **in
	}
	if in.CertificateIDs != nil {
		in, out := &in.CertificateIDs, &out.CertificateIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ClientCertificateID != nil {
		in, out := &in.ClientCertificateID, &out.ClientCertificateID
		*out = new(string)
		**out = **in
	}
	if in.LoadBalancerSpec != nil {
		in, out := &in.LoadBalancerSpec, &out.LoadBalancerSpec
		*out = new(VKSLoadBalancerSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VKSGatewayPolicySpec.
func (in *VKSGatewayPolicySpec) DeepCopy() *VKSGatewayPolicySpec {
	if in == nil {
		return nil
	}
	out := new(VKSGatewayPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VKSGatewayPolicyStatus) DeepCopyInto(out *VKSGatewayPolicyStatus) {
	*out = *in
	in.CommonStatus.DeepCopyInto(&out.CommonStatus)
	in.CommonPolicyStatus.DeepCopyInto(&out.CommonPolicyStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VKSGatewayPolicyStatus.
func (in *VKSGatewayPolicyStatus) DeepCopy() *VKSGatewayPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(VKSGatewayPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VKSHTTPHealthCheck) DeepCopyInto(out *VKSHTTPHealthCheck) {
	*out = *in
	if in.Path != nil {
		in, out := &in.Path, &out.Path
		*out = new(string)
		**out = **in
	}
	if in.Host != nil {
		in, out := &in.Host, &out.Host
		*out = new(string)
		**out = **in
	}
	if in.ExpectedCodes != nil {
		in, out := &in.ExpectedCodes, &out.ExpectedCodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Method != nil {
		in, out := &in.Method, &out.Method
		*out = new(string)
		**out = **in
	}
	if in.HTTPVersion != nil {
		in, out := &in.HTTPVersion, &out.HTTPVersion
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VKSHTTPHealthCheck.
func (in *VKSHTTPHealthCheck) DeepCopy() *VKSHTTPHealthCheck {
	if in == nil {
		return nil
	}
	out := new(VKSHTTPHealthCheck)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VKSHealthCheckPolicy) DeepCopyInto(out *VKSHealthCheckPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VKSHealthCheckPolicy.
func (in *VKSHealthCheckPolicy) DeepCopy() *VKSHealthCheckPolicy {
	if in == nil {
		return nil
	}
	out := new(VKSHealthCheckPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VKSHealthCheckPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VKSHealthCheckPolicyList) DeepCopyInto(out *VKSHealthCheckPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VKSHealthCheckPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VKSHealthCheckPolicyList.
func (in *VKSHealthCheckPolicyList) DeepCopy() *VKSHealthCheckPolicyList {
	if in == nil {
		return nil
	}
	out := new(VKSHealthCheckPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VKSHealthCheckPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VKSHealthCheckPolicySpec) DeepCopyInto(out *VKSHealthCheckPolicySpec) {
	*out = *in
	if in.TargetRefs != nil {
		in, out := &in.TargetRefs, &out.TargetRefs
		*out = make([]v1alpha2.LocalPolicyTargetReference, len(*in))
		copy(*out, *in)
	}
	if in.Interval != nil {
		in, out := &in.Interval, &out.Interval
		*out = new(v1.Duration)
		**out = **in
	}
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(v1.Duration)
		**out = **in
	}
	if in.HealthyThreshold != nil {
		in, out := &in.HealthyThreshold, &out.HealthyThreshold
		*out = new(int32)
		**out = **in
	}
	if in.UnhealthyThreshold != nil {
		in, out := &in.UnhealthyThreshold, &out.UnhealthyThreshold
		*out = new(int32)
		**out = **in
	}
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(int32)
		**out = **in
	}
	if in.HTTPHealthCheck != nil {
		in, out := &in.HTTPHealthCheck, &out.HTTPHealthCheck
		*out = new(VKSHTTPHealthCheck)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VKSHealthCheckPolicySpec.
func (in *VKSHealthCheckPolicySpec) DeepCopy() *VKSHealthCheckPolicySpec {
	if in == nil {
		return nil
	}
	out := new(VKSHealthCheckPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VKSHealthCheckPolicyStatus) DeepCopyInto(out *VKSHealthCheckPolicyStatus) {
	*out = *in
	in.CommonStatus.DeepCopyInto(&out.CommonStatus)
	in.CommonPolicyStatus.DeepCopyInto(&out.CommonPolicyStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VKSHealthCheckPolicyStatus.
func (in *VKSHealthCheckPolicyStatus) DeepCopy() *VKSHealthCheckPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(VKSHealthCheckPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VKSLoadBalancerSpec) DeepCopyInto(out *VKSLoadBalancerSpec) {
	*out = *in
	if in.Scheme != nil {
		in, out := &in.Scheme, &out.Scheme
		*out = new(string)
		**out = **in
	}
	if in.PackageID != nil {
		in, out := &in.PackageID, &out.PackageID
		*out = new(string)
		**out = **in
	}
	if in.SubnetID != nil {
		in, out := &in.SubnetID, &out.SubnetID
		*out = new(string)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.LoadBalancerID != nil {
		in, out := &in.LoadBalancerID, &out.LoadBalancerID
		*out = new(string)
		**out = **in
	}
	if in.LoadBalancerName != nil {
		in, out := &in.LoadBalancerName, &out.LoadBalancerName
		*out = new(string)
		**out = **in
	}
	if in.PreferZoneID != nil {
		in, out := &in.PreferZoneID, &out.PreferZoneID
		*out = new(string)
		**out = **in
	}
	if in.PrivateSubnetID != nil {
		in, out := &in.PrivateSubnetID, &out.PrivateSubnetID
		*out = new(string)
		**out = **in
	}
	if in.PrivateZoneID != nil {
		in, out := &in.PrivateZoneID, &out.PrivateZoneID
		*out = new(string)
		**out = **in
	}
	if in.EnableAutoscale != nil {
		in, out := &in.EnableAutoscale, &out.EnableAutoscale
		*out = new(bool)
		**out = **in
	}
	if in.IsPOC != nil {
		in, out := &in.IsPOC, &out.IsPOC
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VKSLoadBalancerSpec.
func (in *VKSLoadBalancerSpec) DeepCopy() *VKSLoadBalancerSpec {
	if in == nil {
		return nil
	}
	out := new(VKSLoadBalancerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VKSRedirectAction) DeepCopyInto(out *VKSRedirectAction) {
	*out = *in
	if in.HTTPCode != nil {
		in, out := &in.HTTPCode, &out.HTTPCode
		*out = new(int32)
		**out = **in
	}
	if in.KeepQueryString != nil {
		in, out := &in.KeepQueryString, &out.KeepQueryString
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VKSRedirectAction.
func (in *VKSRedirectAction) DeepCopy() *VKSRedirectAction {
	if in == nil {
		return nil
	}
	out := new(VKSRedirectAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VKSRoutePolicy) DeepCopyInto(out *VKSRoutePolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VKSRoutePolicy.
func (in *VKSRoutePolicy) DeepCopy() *VKSRoutePolicy {
	if in == nil {
		return nil
	}
	out := new(VKSRoutePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VKSRoutePolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VKSRoutePolicyList) DeepCopyInto(out *VKSRoutePolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VKSRoutePolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VKSRoutePolicyList.
func (in *VKSRoutePolicyList) DeepCopy() *VKSRoutePolicyList {
	if in == nil {
		return nil
	}
	out := new(VKSRoutePolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VKSRoutePolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VKSRoutePolicySpec) DeepCopyInto(out *VKSRoutePolicySpec) {
	*out = *in
	if in.TargetRefs != nil {
		in, out := &in.TargetRefs, &out.TargetRefs
		*out = make([]v1alpha2.LocalPolicyTargetReferenceWithSectionName, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Actions != nil {
		in, out := &in.Actions, &out.Actions
		*out = make([]VKSRuleAction, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Position != nil {
		in, out := &in.Position, &out.Position
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VKSRoutePolicySpec.
func (in *VKSRoutePolicySpec) DeepCopy() *VKSRoutePolicySpec {
	if in == nil {
		return nil
	}
	out := new(VKSRoutePolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VKSRoutePolicyStatus) DeepCopyInto(out *VKSRoutePolicyStatus) {
	*out = *in
	in.CommonStatus.DeepCopyInto(&out.CommonStatus)
	in.CommonPolicyStatus.DeepCopyInto(&out.CommonPolicyStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VKSRoutePolicyStatus.
func (in *VKSRoutePolicyStatus) DeepCopy() *VKSRoutePolicyStatus {
	if in == nil {
		return nil
	}
	out := new(VKSRoutePolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VKSRuleAction) DeepCopyInto(out *VKSRuleAction) {
	*out = *in
	if in.Redirect != nil {
		in, out := &in.Redirect, &out.Redirect
		*out = new(VKSRedirectAction)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VKSRuleAction.
func (in *VKSRuleAction) DeepCopy() *VKSRuleAction {
	if in == nil {
		return nil
	}
	out := new(VKSRuleAction)
	in.DeepCopyInto(out)
	return out
}
