// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package usecase

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"sigs.k8s.io/controller-runtime"
)

// NewMockServiceUseCase creates a new instance of MockServiceUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockServiceUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockServiceUseCase {
	mock := &MockServiceUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockServiceUseCase is an autogenerated mock type for the ServiceUseCase type
type MockServiceUseCase struct {
	mock.Mock
}

type MockServiceUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockServiceUseCase) EXPECT() *MockServiceUseCase_Expecter {
	return &MockServiceUseCase_Expecter{mock: &_m.Mock}
}

// DeleteServiceUseCase provides a mock function for the type MockServiceUseCase
func (_mock *MockServiceUseCase) DeleteServiceUseCase(ctx context.Context, req controllerruntime.Request) error {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for DeleteServiceUseCase")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, controllerruntime.Request) error); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockServiceUseCase_DeleteServiceUseCase_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteServiceUseCase'
type MockServiceUseCase_DeleteServiceUseCase_Call struct {
	*mock.Call
}

// DeleteServiceUseCase is a helper method to define mock.On call
//   - ctx context.Context
//   - req controllerruntime.Request
func (_e *MockServiceUseCase_Expecter) DeleteServiceUseCase(ctx interface{}, req interface{}) *MockServiceUseCase_DeleteServiceUseCase_Call {
	return &MockServiceUseCase_DeleteServiceUseCase_Call{Call: _e.mock.On("DeleteServiceUseCase", ctx, req)}
}

func (_c *MockServiceUseCase_DeleteServiceUseCase_Call) Run(run func(ctx context.Context, req controllerruntime.Request)) *MockServiceUseCase_DeleteServiceUseCase_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 controllerruntime.Request
		if args[1] != nil {
			arg1 = args[1].(controllerruntime.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockServiceUseCase_DeleteServiceUseCase_Call) Return(err error) *MockServiceUseCase_DeleteServiceUseCase_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockServiceUseCase_DeleteServiceUseCase_Call) RunAndReturn(run func(ctx context.Context, req controllerruntime.Request) error) *MockServiceUseCase_DeleteServiceUseCase_Call {
	_c.Call.Return(run)
	return _c
}

// EnsureServiceUseCase provides a mock function for the type MockServiceUseCase
func (_mock *MockServiceUseCase) EnsureServiceUseCase(ctx context.Context, req controllerruntime.Request) error {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for EnsureServiceUseCase")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, controllerruntime.Request) error); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockServiceUseCase_EnsureServiceUseCase_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnsureServiceUseCase'
type MockServiceUseCase_EnsureServiceUseCase_Call struct {
	*mock.Call
}

// EnsureServiceUseCase is a helper method to define mock.On call
//   - ctx context.Context
//   - req controllerruntime.Request
func (_e *MockServiceUseCase_Expecter) EnsureServiceUseCase(ctx interface{}, req interface{}) *MockServiceUseCase_EnsureServiceUseCase_Call {
	return &MockServiceUseCase_EnsureServiceUseCase_Call{Call: _e.mock.On("EnsureServiceUseCase", ctx, req)}
}

func (_c *MockServiceUseCase_EnsureServiceUseCase_Call) Run(run func(ctx context.Context, req controllerruntime.Request)) *MockServiceUseCase_EnsureServiceUseCase_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 controllerruntime.Request
		if args[1] != nil {
			arg1 = args[1].(controllerruntime.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockServiceUseCase_EnsureServiceUseCase_Call) Return(err error) *MockServiceUseCase_EnsureServiceUseCase_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockServiceUseCase_EnsureServiceUseCase_Call) RunAndReturn(run func(ctx context.Context, req controllerruntime.Request) error) *MockServiceUseCase_EnsureServiceUseCase_Call {
	_c.Call.Return(run)
	return _c
}

// InitServiceUseCase provides a mock function for the type MockServiceUseCase
func (_mock *MockServiceUseCase) InitServiceUseCase(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for InitServiceUseCase")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockServiceUseCase_InitServiceUseCase_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InitServiceUseCase'
type MockServiceUseCase_InitServiceUseCase_Call struct {
	*mock.Call
}

// InitServiceUseCase is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockServiceUseCase_Expecter) InitServiceUseCase(ctx interface{}) *MockServiceUseCase_InitServiceUseCase_Call {
	return &MockServiceUseCase_InitServiceUseCase_Call{Call: _e.mock.On("InitServiceUseCase", ctx)}
}

func (_c *MockServiceUseCase_InitServiceUseCase_Call) Run(run func(ctx context.Context)) *MockServiceUseCase_InitServiceUseCase_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockServiceUseCase_InitServiceUseCase_Call) Return(err error) *MockServiceUseCase_InitServiceUseCase_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockServiceUseCase_InitServiceUseCase_Call) RunAndReturn(run func(ctx context.Context) error) *MockServiceUseCase_InitServiceUseCase_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLoadBalancerConfigUseCase creates a new instance of MockLoadBalancerConfigUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLoadBalancerConfigUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLoadBalancerConfigUseCase {
	mock := &MockLoadBalancerConfigUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLoadBalancerConfigUseCase is an autogenerated mock type for the LoadBalancerConfigUseCase type
type MockLoadBalancerConfigUseCase struct {
	mock.Mock
}

type MockLoadBalancerConfigUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLoadBalancerConfigUseCase) EXPECT() *MockLoadBalancerConfigUseCase_Expecter {
	return &MockLoadBalancerConfigUseCase_Expecter{mock: &_m.Mock}
}

// DeleteLoadBalancerConfigUseCase provides a mock function for the type MockLoadBalancerConfigUseCase
func (_mock *MockLoadBalancerConfigUseCase) DeleteLoadBalancerConfigUseCase(ctx context.Context, req controllerruntime.Request) error {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for DeleteLoadBalancerConfigUseCase")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, controllerruntime.Request) error); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLoadBalancerConfigUseCase_DeleteLoadBalancerConfigUseCase_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteLoadBalancerConfigUseCase'
type MockLoadBalancerConfigUseCase_DeleteLoadBalancerConfigUseCase_Call struct {
	*mock.Call
}

// DeleteLoadBalancerConfigUseCase is a helper method to define mock.On call
//   - ctx context.Context
//   - req controllerruntime.Request
func (_e *MockLoadBalancerConfigUseCase_Expecter) DeleteLoadBalancerConfigUseCase(ctx interface{}, req interface{}) *MockLoadBalancerConfigUseCase_DeleteLoadBalancerConfigUseCase_Call {
	return &MockLoadBalancerConfigUseCase_DeleteLoadBalancerConfigUseCase_Call{Call: _e.mock.On("DeleteLoadBalancerConfigUseCase", ctx, req)}
}

func (_c *MockLoadBalancerConfigUseCase_DeleteLoadBalancerConfigUseCase_Call) Run(run func(ctx context.Context, req controllerruntime.Request)) *MockLoadBalancerConfigUseCase_DeleteLoadBalancerConfigUseCase_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 controllerruntime.Request
		if args[1] != nil {
			arg1 = args[1].(controllerruntime.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLoadBalancerConfigUseCase_DeleteLoadBalancerConfigUseCase_Call) Return(err error) *MockLoadBalancerConfigUseCase_DeleteLoadBalancerConfigUseCase_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLoadBalancerConfigUseCase_DeleteLoadBalancerConfigUseCase_Call) RunAndReturn(run func(ctx context.Context, req controllerruntime.Request) error) *MockLoadBalancerConfigUseCase_DeleteLoadBalancerConfigUseCase_Call {
	_c.Call.Return(run)
	return _c
}

// EnsureLoadBalancerConfigUseCase provides a mock function for the type MockLoadBalancerConfigUseCase
func (_mock *MockLoadBalancerConfigUseCase) EnsureLoadBalancerConfigUseCase(ctx context.Context, req controllerruntime.Request) error {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for EnsureLoadBalancerConfigUseCase")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, controllerruntime.Request) error); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLoadBalancerConfigUseCase_EnsureLoadBalancerConfigUseCase_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnsureLoadBalancerConfigUseCase'
type MockLoadBalancerConfigUseCase_EnsureLoadBalancerConfigUseCase_Call struct {
	*mock.Call
}

// EnsureLoadBalancerConfigUseCase is a helper method to define mock.On call
//   - ctx context.Context
//   - req controllerruntime.Request
func (_e *MockLoadBalancerConfigUseCase_Expecter) EnsureLoadBalancerConfigUseCase(ctx interface{}, req interface{}) *MockLoadBalancerConfigUseCase_EnsureLoadBalancerConfigUseCase_Call {
	return &MockLoadBalancerConfigUseCase_EnsureLoadBalancerConfigUseCase_Call{Call: _e.mock.On("EnsureLoadBalancerConfigUseCase", ctx, req)}
}

func (_c *MockLoadBalancerConfigUseCase_EnsureLoadBalancerConfigUseCase_Call) Run(run func(ctx context.Context, req controllerruntime.Request)) *MockLoadBalancerConfigUseCase_EnsureLoadBalancerConfigUseCase_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 controllerruntime.Request
		if args[1] != nil {
			arg1 = args[1].(controllerruntime.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLoadBalancerConfigUseCase_EnsureLoadBalancerConfigUseCase_Call) Return(err error) *MockLoadBalancerConfigUseCase_EnsureLoadBalancerConfigUseCase_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLoadBalancerConfigUseCase_EnsureLoadBalancerConfigUseCase_Call) RunAndReturn(run func(ctx context.Context, req controllerruntime.Request) error) *MockLoadBalancerConfigUseCase_EnsureLoadBalancerConfigUseCase_Call {
	_c.Call.Return(run)
	return _c
}

// InitLoadBalancerConfigUseCase provides a mock function for the type MockLoadBalancerConfigUseCase
func (_mock *MockLoadBalancerConfigUseCase) InitLoadBalancerConfigUseCase(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for InitLoadBalancerConfigUseCase")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLoadBalancerConfigUseCase_InitLoadBalancerConfigUseCase_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InitLoadBalancerConfigUseCase'
type MockLoadBalancerConfigUseCase_InitLoadBalancerConfigUseCase_Call struct {
	*mock.Call
}

// InitLoadBalancerConfigUseCase is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockLoadBalancerConfigUseCase_Expecter) InitLoadBalancerConfigUseCase(ctx interface{}) *MockLoadBalancerConfigUseCase_InitLoadBalancerConfigUseCase_Call {
	return &MockLoadBalancerConfigUseCase_InitLoadBalancerConfigUseCase_Call{Call: _e.mock.On("InitLoadBalancerConfigUseCase", ctx)}
}

func (_c *MockLoadBalancerConfigUseCase_InitLoadBalancerConfigUseCase_Call) Run(run func(ctx context.Context)) *MockLoadBalancerConfigUseCase_InitLoadBalancerConfigUseCase_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockLoadBalancerConfigUseCase_InitLoadBalancerConfigUseCase_Call) Return(err error) *MockLoadBalancerConfigUseCase_InitLoadBalancerConfigUseCase_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLoadBalancerConfigUseCase_InitLoadBalancerConfigUseCase_Call) RunAndReturn(run func(ctx context.Context) error) *MockLoadBalancerConfigUseCase_InitLoadBalancerConfigUseCase_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockNodeSecurityGroupUseCase creates a new instance of MockNodeSecurityGroupUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNodeSecurityGroupUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNodeSecurityGroupUseCase {
	mock := &MockNodeSecurityGroupUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockNodeSecurityGroupUseCase is an autogenerated mock type for the NodeSecurityGroupUseCase type
type MockNodeSecurityGroupUseCase struct {
	mock.Mock
}

type MockNodeSecurityGroupUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNodeSecurityGroupUseCase) EXPECT() *MockNodeSecurityGroupUseCase_Expecter {
	return &MockNodeSecurityGroupUseCase_Expecter{mock: &_m.Mock}
}

// DeleteNodeSecurityGroupUseCase provides a mock function for the type MockNodeSecurityGroupUseCase
func (_mock *MockNodeSecurityGroupUseCase) DeleteNodeSecurityGroupUseCase(ctx context.Context, req controllerruntime.Request) error {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for DeleteNodeSecurityGroupUseCase")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, controllerruntime.Request) error); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNodeSecurityGroupUseCase_DeleteNodeSecurityGroupUseCase_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteNodeSecurityGroupUseCase'
type MockNodeSecurityGroupUseCase_DeleteNodeSecurityGroupUseCase_Call struct {
	*mock.Call
}

// DeleteNodeSecurityGroupUseCase is a helper method to define mock.On call
//   - ctx context.Context
//   - req controllerruntime.Request
func (_e *MockNodeSecurityGroupUseCase_Expecter) DeleteNodeSecurityGroupUseCase(ctx interface{}, req interface{}) *MockNodeSecurityGroupUseCase_DeleteNodeSecurityGroupUseCase_Call {
	return &MockNodeSecurityGroupUseCase_DeleteNodeSecurityGroupUseCase_Call{Call: _e.mock.On("DeleteNodeSecurityGroupUseCase", ctx, req)}
}

func (_c *MockNodeSecurityGroupUseCase_DeleteNodeSecurityGroupUseCase_Call) Run(run func(ctx context.Context, req controllerruntime.Request)) *MockNodeSecurityGroupUseCase_DeleteNodeSecurityGroupUseCase_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 controllerruntime.Request
		if args[1] != nil {
			arg1 = args[1].(controllerruntime.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNodeSecurityGroupUseCase_DeleteNodeSecurityGroupUseCase_Call) Return(err error) *MockNodeSecurityGroupUseCase_DeleteNodeSecurityGroupUseCase_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNodeSecurityGroupUseCase_DeleteNodeSecurityGroupUseCase_Call) RunAndReturn(run func(ctx context.Context, req controllerruntime.Request) error) *MockNodeSecurityGroupUseCase_DeleteNodeSecurityGroupUseCase_Call {
	_c.Call.Return(run)
	return _c
}

// EnsureNodeSecurityGroupUseCase provides a mock function for the type MockNodeSecurityGroupUseCase
func (_mock *MockNodeSecurityGroupUseCase) EnsureNodeSecurityGroupUseCase(ctx context.Context, req controllerruntime.Request) error {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for EnsureNodeSecurityGroupUseCase")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, controllerruntime.Request) error); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNodeSecurityGroupUseCase_EnsureNodeSecurityGroupUseCase_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnsureNodeSecurityGroupUseCase'
type MockNodeSecurityGroupUseCase_EnsureNodeSecurityGroupUseCase_Call struct {
	*mock.Call
}

// EnsureNodeSecurityGroupUseCase is a helper method to define mock.On call
//   - ctx context.Context
//   - req controllerruntime.Request
func (_e *MockNodeSecurityGroupUseCase_Expecter) EnsureNodeSecurityGroupUseCase(ctx interface{}, req interface{}) *MockNodeSecurityGroupUseCase_EnsureNodeSecurityGroupUseCase_Call {
	return &MockNodeSecurityGroupUseCase_EnsureNodeSecurityGroupUseCase_Call{Call: _e.mock.On("EnsureNodeSecurityGroupUseCase", ctx, req)}
}

func (_c *MockNodeSecurityGroupUseCase_EnsureNodeSecurityGroupUseCase_Call) Run(run func(ctx context.Context, req controllerruntime.Request)) *MockNodeSecurityGroupUseCase_EnsureNodeSecurityGroupUseCase_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 controllerruntime.Request
		if args[1] != nil {
			arg1 = args[1].(controllerruntime.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNodeSecurityGroupUseCase_EnsureNodeSecurityGroupUseCase_Call) Return(err error) *MockNodeSecurityGroupUseCase_EnsureNodeSecurityGroupUseCase_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNodeSecurityGroupUseCase_EnsureNodeSecurityGroupUseCase_Call) RunAndReturn(run func(ctx context.Context, req controllerruntime.Request) error) *MockNodeSecurityGroupUseCase_EnsureNodeSecurityGroupUseCase_Call {
	_c.Call.Return(run)
	return _c
}

// InitNodeSecurityGroupUseCase provides a mock function for the type MockNodeSecurityGroupUseCase
func (_mock *MockNodeSecurityGroupUseCase) InitNodeSecurityGroupUseCase(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for InitNodeSecurityGroupUseCase")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNodeSecurityGroupUseCase_InitNodeSecurityGroupUseCase_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InitNodeSecurityGroupUseCase'
type MockNodeSecurityGroupUseCase_InitNodeSecurityGroupUseCase_Call struct {
	*mock.Call
}

// InitNodeSecurityGroupUseCase is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockNodeSecurityGroupUseCase_Expecter) InitNodeSecurityGroupUseCase(ctx interface{}) *MockNodeSecurityGroupUseCase_InitNodeSecurityGroupUseCase_Call {
	return &MockNodeSecurityGroupUseCase_InitNodeSecurityGroupUseCase_Call{Call: _e.mock.On("InitNodeSecurityGroupUseCase", ctx)}
}

func (_c *MockNodeSecurityGroupUseCase_InitNodeSecurityGroupUseCase_Call) Run(run func(ctx context.Context)) *MockNodeSecurityGroupUseCase_InitNodeSecurityGroupUseCase_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockNodeSecurityGroupUseCase_InitNodeSecurityGroupUseCase_Call) Return(err error) *MockNodeSecurityGroupUseCase_InitNodeSecurityGroupUseCase_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNodeSecurityGroupUseCase_InitNodeSecurityGroupUseCase_Call) RunAndReturn(run func(ctx context.Context) error) *MockNodeSecurityGroupUseCase_InitNodeSecurityGroupUseCase_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIngressUseCase creates a new instance of MockIngressUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIngressUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIngressUseCase {
	mock := &MockIngressUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIngressUseCase is an autogenerated mock type for the IngressUseCase type
type MockIngressUseCase struct {
	mock.Mock
}

type MockIngressUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIngressUseCase) EXPECT() *MockIngressUseCase_Expecter {
	return &MockIngressUseCase_Expecter{mock: &_m.Mock}
}

// DeleteIngressUseCase provides a mock function for the type MockIngressUseCase
func (_mock *MockIngressUseCase) DeleteIngressUseCase(ctx context.Context, req controllerruntime.Request) error {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for DeleteIngressUseCase")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, controllerruntime.Request) error); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIngressUseCase_DeleteIngressUseCase_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteIngressUseCase'
type MockIngressUseCase_DeleteIngressUseCase_Call struct {
	*mock.Call
}

// DeleteIngressUseCase is a helper method to define mock.On call
//   - ctx context.Context
//   - req controllerruntime.Request
func (_e *MockIngressUseCase_Expecter) DeleteIngressUseCase(ctx interface{}, req interface{}) *MockIngressUseCase_DeleteIngressUseCase_Call {
	return &MockIngressUseCase_DeleteIngressUseCase_Call{Call: _e.mock.On("DeleteIngressUseCase", ctx, req)}
}

func (_c *MockIngressUseCase_DeleteIngressUseCase_Call) Run(run func(ctx context.Context, req controllerruntime.Request)) *MockIngressUseCase_DeleteIngressUseCase_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 controllerruntime.Request
		if args[1] != nil {
			arg1 = args[1].(controllerruntime.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIngressUseCase_DeleteIngressUseCase_Call) Return(err error) *MockIngressUseCase_DeleteIngressUseCase_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIngressUseCase_DeleteIngressUseCase_Call) RunAndReturn(run func(ctx context.Context, req controllerruntime.Request) error) *MockIngressUseCase_DeleteIngressUseCase_Call {
	_c.Call.Return(run)
	return _c
}

// EnsureIngressUseCase provides a mock function for the type MockIngressUseCase
func (_mock *MockIngressUseCase) EnsureIngressUseCase(ctx context.Context, req controllerruntime.Request) error {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for EnsureIngressUseCase")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, controllerruntime.Request) error); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIngressUseCase_EnsureIngressUseCase_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnsureIngressUseCase'
type MockIngressUseCase_EnsureIngressUseCase_Call struct {
	*mock.Call
}

// EnsureIngressUseCase is a helper method to define mock.On call
//   - ctx context.Context
//   - req controllerruntime.Request
func (_e *MockIngressUseCase_Expecter) EnsureIngressUseCase(ctx interface{}, req interface{}) *MockIngressUseCase_EnsureIngressUseCase_Call {
	return &MockIngressUseCase_EnsureIngressUseCase_Call{Call: _e.mock.On("EnsureIngressUseCase", ctx, req)}
}

func (_c *MockIngressUseCase_EnsureIngressUseCase_Call) Run(run func(ctx context.Context, req controllerruntime.Request)) *MockIngressUseCase_EnsureIngressUseCase_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 controllerruntime.Request
		if args[1] != nil {
			arg1 = args[1].(controllerruntime.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIngressUseCase_EnsureIngressUseCase_Call) Return(err error) *MockIngressUseCase_EnsureIngressUseCase_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIngressUseCase_EnsureIngressUseCase_Call) RunAndReturn(run func(ctx context.Context, req controllerruntime.Request) error) *MockIngressUseCase_EnsureIngressUseCase_Call {
	_c.Call.Return(run)
	return _c
}

// InitIngressUseCase provides a mock function for the type MockIngressUseCase
func (_mock *MockIngressUseCase) InitIngressUseCase(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for InitIngressUseCase")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIngressUseCase_InitIngressUseCase_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InitIngressUseCase'
type MockIngressUseCase_InitIngressUseCase_Call struct {
	*mock.Call
}

// InitIngressUseCase is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIngressUseCase_Expecter) InitIngressUseCase(ctx interface{}) *MockIngressUseCase_InitIngressUseCase_Call {
	return &MockIngressUseCase_InitIngressUseCase_Call{Call: _e.mock.On("InitIngressUseCase", ctx)}
}

func (_c *MockIngressUseCase_InitIngressUseCase_Call) Run(run func(ctx context.Context)) *MockIngressUseCase_InitIngressUseCase_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIngressUseCase_InitIngressUseCase_Call) Return(err error) *MockIngressUseCase_InitIngressUseCase_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIngressUseCase_InitIngressUseCase_Call) RunAndReturn(run func(ctx context.Context) error) *MockIngressUseCase_InitIngressUseCase_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockVngcloudGlobalLoadBalancerUseCase creates a new instance of MockVngcloudGlobalLoadBalancerUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVngcloudGlobalLoadBalancerUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVngcloudGlobalLoadBalancerUseCase {
	mock := &MockVngcloudGlobalLoadBalancerUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockVngcloudGlobalLoadBalancerUseCase is an autogenerated mock type for the VngcloudGlobalLoadBalancerUseCase type
type MockVngcloudGlobalLoadBalancerUseCase struct {
	mock.Mock
}

type MockVngcloudGlobalLoadBalancerUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVngcloudGlobalLoadBalancerUseCase) EXPECT() *MockVngcloudGlobalLoadBalancerUseCase_Expecter {
	return &MockVngcloudGlobalLoadBalancerUseCase_Expecter{mock: &_m.Mock}
}

// DeleteVngcloudGlobalLoadBalancerUseCase provides a mock function for the type MockVngcloudGlobalLoadBalancerUseCase
func (_mock *MockVngcloudGlobalLoadBalancerUseCase) DeleteVngcloudGlobalLoadBalancerUseCase(ctx context.Context, req controllerruntime.Request) error {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for DeleteVngcloudGlobalLoadBalancerUseCase")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, controllerruntime.Request) error); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockVngcloudGlobalLoadBalancerUseCase_DeleteVngcloudGlobalLoadBalancerUseCase_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteVngcloudGlobalLoadBalancerUseCase'
type MockVngcloudGlobalLoadBalancerUseCase_DeleteVngcloudGlobalLoadBalancerUseCase_Call struct {
	*mock.Call
}

// DeleteVngcloudGlobalLoadBalancerUseCase is a helper method to define mock.On call
//   - ctx context.Context
//   - req controllerruntime.Request
func (_e *MockVngcloudGlobalLoadBalancerUseCase_Expecter) DeleteVngcloudGlobalLoadBalancerUseCase(ctx interface{}, req interface{}) *MockVngcloudGlobalLoadBalancerUseCase_DeleteVngcloudGlobalLoadBalancerUseCase_Call {
	return &MockVngcloudGlobalLoadBalancerUseCase_DeleteVngcloudGlobalLoadBalancerUseCase_Call{Call: _e.mock.On("DeleteVngcloudGlobalLoadBalancerUseCase", ctx, req)}
}

func (_c *MockVngcloudGlobalLoadBalancerUseCase_DeleteVngcloudGlobalLoadBalancerUseCase_Call) Run(run func(ctx context.Context, req controllerruntime.Request)) *MockVngcloudGlobalLoadBalancerUseCase_DeleteVngcloudGlobalLoadBalancerUseCase_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 controllerruntime.Request
		if args[1] != nil {
			arg1 = args[1].(controllerruntime.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockVngcloudGlobalLoadBalancerUseCase_DeleteVngcloudGlobalLoadBalancerUseCase_Call) Return(err error) *MockVngcloudGlobalLoadBalancerUseCase_DeleteVngcloudGlobalLoadBalancerUseCase_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockVngcloudGlobalLoadBalancerUseCase_DeleteVngcloudGlobalLoadBalancerUseCase_Call) RunAndReturn(run func(ctx context.Context, req controllerruntime.Request) error) *MockVngcloudGlobalLoadBalancerUseCase_DeleteVngcloudGlobalLoadBalancerUseCase_Call {
	_c.Call.Return(run)
	return _c
}

// EnsureVngcloudGlobalLoadBalancerUseCase provides a mock function for the type MockVngcloudGlobalLoadBalancerUseCase
func (_mock *MockVngcloudGlobalLoadBalancerUseCase) EnsureVngcloudGlobalLoadBalancerUseCase(ctx context.Context, req controllerruntime.Request) error {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for EnsureVngcloudGlobalLoadBalancerUseCase")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, controllerruntime.Request) error); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockVngcloudGlobalLoadBalancerUseCase_EnsureVngcloudGlobalLoadBalancerUseCase_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnsureVngcloudGlobalLoadBalancerUseCase'
type MockVngcloudGlobalLoadBalancerUseCase_EnsureVngcloudGlobalLoadBalancerUseCase_Call struct {
	*mock.Call
}

// EnsureVngcloudGlobalLoadBalancerUseCase is a helper method to define mock.On call
//   - ctx context.Context
//   - req controllerruntime.Request
func (_e *MockVngcloudGlobalLoadBalancerUseCase_Expecter) EnsureVngcloudGlobalLoadBalancerUseCase(ctx interface{}, req interface{}) *MockVngcloudGlobalLoadBalancerUseCase_EnsureVngcloudGlobalLoadBalancerUseCase_Call {
	return &MockVngcloudGlobalLoadBalancerUseCase_EnsureVngcloudGlobalLoadBalancerUseCase_Call{Call: _e.mock.On("EnsureVngcloudGlobalLoadBalancerUseCase", ctx, req)}
}

func (_c *MockVngcloudGlobalLoadBalancerUseCase_EnsureVngcloudGlobalLoadBalancerUseCase_Call) Run(run func(ctx context.Context, req controllerruntime.Request)) *MockVngcloudGlobalLoadBalancerUseCase_EnsureVngcloudGlobalLoadBalancerUseCase_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 controllerruntime.Request
		if args[1] != nil {
			arg1 = args[1].(controllerruntime.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockVngcloudGlobalLoadBalancerUseCase_EnsureVngcloudGlobalLoadBalancerUseCase_Call) Return(err error) *MockVngcloudGlobalLoadBalancerUseCase_EnsureVngcloudGlobalLoadBalancerUseCase_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockVngcloudGlobalLoadBalancerUseCase_EnsureVngcloudGlobalLoadBalancerUseCase_Call) RunAndReturn(run func(ctx context.Context, req controllerruntime.Request) error) *MockVngcloudGlobalLoadBalancerUseCase_EnsureVngcloudGlobalLoadBalancerUseCase_Call {
	_c.Call.Return(run)
	return _c
}

// InitVngcloudGlobalLoadBalancerUseCase provides a mock function for the type MockVngcloudGlobalLoadBalancerUseCase
func (_mock *MockVngcloudGlobalLoadBalancerUseCase) InitVngcloudGlobalLoadBalancerUseCase(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for InitVngcloudGlobalLoadBalancerUseCase")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockVngcloudGlobalLoadBalancerUseCase_InitVngcloudGlobalLoadBalancerUseCase_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InitVngcloudGlobalLoadBalancerUseCase'
type MockVngcloudGlobalLoadBalancerUseCase_InitVngcloudGlobalLoadBalancerUseCase_Call struct {
	*mock.Call
}

// InitVngcloudGlobalLoadBalancerUseCase is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockVngcloudGlobalLoadBalancerUseCase_Expecter) InitVngcloudGlobalLoadBalancerUseCase(ctx interface{}) *MockVngcloudGlobalLoadBalancerUseCase_InitVngcloudGlobalLoadBalancerUseCase_Call {
	return &MockVngcloudGlobalLoadBalancerUseCase_InitVngcloudGlobalLoadBalancerUseCase_Call{Call: _e.mock.On("InitVngcloudGlobalLoadBalancerUseCase", ctx)}
}

func (_c *MockVngcloudGlobalLoadBalancerUseCase_InitVngcloudGlobalLoadBalancerUseCase_Call) Run(run func(ctx context.Context)) *MockVngcloudGlobalLoadBalancerUseCase_InitVngcloudGlobalLoadBalancerUseCase_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockVngcloudGlobalLoadBalancerUseCase_InitVngcloudGlobalLoadBalancerUseCase_Call) Return(err error) *MockVngcloudGlobalLoadBalancerUseCase_InitVngcloudGlobalLoadBalancerUseCase_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockVngcloudGlobalLoadBalancerUseCase_InitVngcloudGlobalLoadBalancerUseCase_Call) RunAndReturn(run func(ctx context.Context) error) *MockVngcloudGlobalLoadBalancerUseCase_InitVngcloudGlobalLoadBalancerUseCase_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGlobalLoadBalancerConfigUseCase creates a new instance of MockGlobalLoadBalancerConfigUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGlobalLoadBalancerConfigUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGlobalLoadBalancerConfigUseCase {
	mock := &MockGlobalLoadBalancerConfigUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGlobalLoadBalancerConfigUseCase is an autogenerated mock type for the GlobalLoadBalancerConfigUseCase type
type MockGlobalLoadBalancerConfigUseCase struct {
	mock.Mock
}

type MockGlobalLoadBalancerConfigUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGlobalLoadBalancerConfigUseCase) EXPECT() *MockGlobalLoadBalancerConfigUseCase_Expecter {
	return &MockGlobalLoadBalancerConfigUseCase_Expecter{mock: &_m.Mock}
}

// DeleteGlobalLoadBalancerConfigUseCase provides a mock function for the type MockGlobalLoadBalancerConfigUseCase
func (_mock *MockGlobalLoadBalancerConfigUseCase) DeleteGlobalLoadBalancerConfigUseCase(ctx context.Context, req controllerruntime.Request) error {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for DeleteGlobalLoadBalancerConfigUseCase")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, controllerruntime.Request) error); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGlobalLoadBalancerConfigUseCase_DeleteGlobalLoadBalancerConfigUseCase_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteGlobalLoadBalancerConfigUseCase'
type MockGlobalLoadBalancerConfigUseCase_DeleteGlobalLoadBalancerConfigUseCase_Call struct {
	*mock.Call
}

// DeleteGlobalLoadBalancerConfigUseCase is a helper method to define mock.On call
//   - ctx context.Context
//   - req controllerruntime.Request
func (_e *MockGlobalLoadBalancerConfigUseCase_Expecter) DeleteGlobalLoadBalancerConfigUseCase(ctx interface{}, req interface{}) *MockGlobalLoadBalancerConfigUseCase_DeleteGlobalLoadBalancerConfigUseCase_Call {
	return &MockGlobalLoadBalancerConfigUseCase_DeleteGlobalLoadBalancerConfigUseCase_Call{Call: _e.mock.On("DeleteGlobalLoadBalancerConfigUseCase", ctx, req)}
}

func (_c *MockGlobalLoadBalancerConfigUseCase_DeleteGlobalLoadBalancerConfigUseCase_Call) Run(run func(ctx context.Context, req controllerruntime.Request)) *MockGlobalLoadBalancerConfigUseCase_DeleteGlobalLoadBalancerConfigUseCase_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 controllerruntime.Request
		if args[1] != nil {
			arg1 = args[1].(controllerruntime.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGlobalLoadBalancerConfigUseCase_DeleteGlobalLoadBalancerConfigUseCase_Call) Return(err error) *MockGlobalLoadBalancerConfigUseCase_DeleteGlobalLoadBalancerConfigUseCase_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGlobalLoadBalancerConfigUseCase_DeleteGlobalLoadBalancerConfigUseCase_Call) RunAndReturn(run func(ctx context.Context, req controllerruntime.Request) error) *MockGlobalLoadBalancerConfigUseCase_DeleteGlobalLoadBalancerConfigUseCase_Call {
	_c.Call.Return(run)
	return _c
}

// EnsureGlobalLoadBalancerConfigUseCase provides a mock function for the type MockGlobalLoadBalancerConfigUseCase
func (_mock *MockGlobalLoadBalancerConfigUseCase) EnsureGlobalLoadBalancerConfigUseCase(ctx context.Context, req controllerruntime.Request) error {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for EnsureGlobalLoadBalancerConfigUseCase")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, controllerruntime.Request) error); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGlobalLoadBalancerConfigUseCase_EnsureGlobalLoadBalancerConfigUseCase_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnsureGlobalLoadBalancerConfigUseCase'
type MockGlobalLoadBalancerConfigUseCase_EnsureGlobalLoadBalancerConfigUseCase_Call struct {
	*mock.Call
}

// EnsureGlobalLoadBalancerConfigUseCase is a helper method to define mock.On call
//   - ctx context.Context
//   - req controllerruntime.Request
func (_e *MockGlobalLoadBalancerConfigUseCase_Expecter) EnsureGlobalLoadBalancerConfigUseCase(ctx interface{}, req interface{}) *MockGlobalLoadBalancerConfigUseCase_EnsureGlobalLoadBalancerConfigUseCase_Call {
	return &MockGlobalLoadBalancerConfigUseCase_EnsureGlobalLoadBalancerConfigUseCase_Call{Call: _e.mock.On("EnsureGlobalLoadBalancerConfigUseCase", ctx, req)}
}

func (_c *MockGlobalLoadBalancerConfigUseCase_EnsureGlobalLoadBalancerConfigUseCase_Call) Run(run func(ctx context.Context, req controllerruntime.Request)) *MockGlobalLoadBalancerConfigUseCase_EnsureGlobalLoadBalancerConfigUseCase_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 controllerruntime.Request
		if args[1] != nil {
			arg1 = args[1].(controllerruntime.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGlobalLoadBalancerConfigUseCase_EnsureGlobalLoadBalancerConfigUseCase_Call) Return(err error) *MockGlobalLoadBalancerConfigUseCase_EnsureGlobalLoadBalancerConfigUseCase_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGlobalLoadBalancerConfigUseCase_EnsureGlobalLoadBalancerConfigUseCase_Call) RunAndReturn(run func(ctx context.Context, req controllerruntime.Request) error) *MockGlobalLoadBalancerConfigUseCase_EnsureGlobalLoadBalancerConfigUseCase_Call {
	_c.Call.Return(run)
	return _c
}

// InitGlobalLoadBalancerConfigUseCase provides a mock function for the type MockGlobalLoadBalancerConfigUseCase
func (_mock *MockGlobalLoadBalancerConfigUseCase) InitGlobalLoadBalancerConfigUseCase(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for InitGlobalLoadBalancerConfigUseCase")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGlobalLoadBalancerConfigUseCase_InitGlobalLoadBalancerConfigUseCase_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InitGlobalLoadBalancerConfigUseCase'
type MockGlobalLoadBalancerConfigUseCase_InitGlobalLoadBalancerConfigUseCase_Call struct {
	*mock.Call
}

// InitGlobalLoadBalancerConfigUseCase is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockGlobalLoadBalancerConfigUseCase_Expecter) InitGlobalLoadBalancerConfigUseCase(ctx interface{}) *MockGlobalLoadBalancerConfigUseCase_InitGlobalLoadBalancerConfigUseCase_Call {
	return &MockGlobalLoadBalancerConfigUseCase_InitGlobalLoadBalancerConfigUseCase_Call{Call: _e.mock.On("InitGlobalLoadBalancerConfigUseCase", ctx)}
}

func (_c *MockGlobalLoadBalancerConfigUseCase_InitGlobalLoadBalancerConfigUseCase_Call) Run(run func(ctx context.Context)) *MockGlobalLoadBalancerConfigUseCase_InitGlobalLoadBalancerConfigUseCase_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockGlobalLoadBalancerConfigUseCase_InitGlobalLoadBalancerConfigUseCase_Call) Return(err error) *MockGlobalLoadBalancerConfigUseCase_InitGlobalLoadBalancerConfigUseCase_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGlobalLoadBalancerConfigUseCase_InitGlobalLoadBalancerConfigUseCase_Call) RunAndReturn(run func(ctx context.Context) error) *MockGlobalLoadBalancerConfigUseCase_InitGlobalLoadBalancerConfigUseCase_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockServiceGLBUseCase creates a new instance of MockServiceGLBUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockServiceGLBUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockServiceGLBUseCase {
	mock := &MockServiceGLBUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockServiceGLBUseCase is an autogenerated mock type for the ServiceGLBUseCase type
type MockServiceGLBUseCase struct {
	mock.Mock
}

type MockServiceGLBUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockServiceGLBUseCase) EXPECT() *MockServiceGLBUseCase_Expecter {
	return &MockServiceGLBUseCase_Expecter{mock: &_m.Mock}
}

// DeleteServiceGLBUseCase provides a mock function for the type MockServiceGLBUseCase
func (_mock *MockServiceGLBUseCase) DeleteServiceGLBUseCase(ctx context.Context, req controllerruntime.Request) error {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for DeleteServiceGLBUseCase")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, controllerruntime.Request) error); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockServiceGLBUseCase_DeleteServiceGLBUseCase_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteServiceGLBUseCase'
type MockServiceGLBUseCase_DeleteServiceGLBUseCase_Call struct {
	*mock.Call
}

// DeleteServiceGLBUseCase is a helper method to define mock.On call
//   - ctx context.Context
//   - req controllerruntime.Request
func (_e *MockServiceGLBUseCase_Expecter) DeleteServiceGLBUseCase(ctx interface{}, req interface{}) *MockServiceGLBUseCase_DeleteServiceGLBUseCase_Call {
	return &MockServiceGLBUseCase_DeleteServiceGLBUseCase_Call{Call: _e.mock.On("DeleteServiceGLBUseCase", ctx, req)}
}

func (_c *MockServiceGLBUseCase_DeleteServiceGLBUseCase_Call) Run(run func(ctx context.Context, req controllerruntime.Request)) *MockServiceGLBUseCase_DeleteServiceGLBUseCase_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 controllerruntime.Request
		if args[1] != nil {
			arg1 = args[1].(controllerruntime.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockServiceGLBUseCase_DeleteServiceGLBUseCase_Call) Return(err error) *MockServiceGLBUseCase_DeleteServiceGLBUseCase_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockServiceGLBUseCase_DeleteServiceGLBUseCase_Call) RunAndReturn(run func(ctx context.Context, req controllerruntime.Request) error) *MockServiceGLBUseCase_DeleteServiceGLBUseCase_Call {
	_c.Call.Return(run)
	return _c
}

// EnsureServiceGLBUseCase provides a mock function for the type MockServiceGLBUseCase
func (_mock *MockServiceGLBUseCase) EnsureServiceGLBUseCase(ctx context.Context, req controllerruntime.Request) error {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for EnsureServiceGLBUseCase")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, controllerruntime.Request) error); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockServiceGLBUseCase_EnsureServiceGLBUseCase_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnsureServiceGLBUseCase'
type MockServiceGLBUseCase_EnsureServiceGLBUseCase_Call struct {
	*mock.Call
}

// EnsureServiceGLBUseCase is a helper method to define mock.On call
//   - ctx context.Context
//   - req controllerruntime.Request
func (_e *MockServiceGLBUseCase_Expecter) EnsureServiceGLBUseCase(ctx interface{}, req interface{}) *MockServiceGLBUseCase_EnsureServiceGLBUseCase_Call {
	return &MockServiceGLBUseCase_EnsureServiceGLBUseCase_Call{Call: _e.mock.On("EnsureServiceGLBUseCase", ctx, req)}
}

func (_c *MockServiceGLBUseCase_EnsureServiceGLBUseCase_Call) Run(run func(ctx context.Context, req controllerruntime.Request)) *MockServiceGLBUseCase_EnsureServiceGLBUseCase_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 controllerruntime.Request
		if args[1] != nil {
			arg1 = args[1].(controllerruntime.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockServiceGLBUseCase_EnsureServiceGLBUseCase_Call) Return(err error) *MockServiceGLBUseCase_EnsureServiceGLBUseCase_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockServiceGLBUseCase_EnsureServiceGLBUseCase_Call) RunAndReturn(run func(ctx context.Context, req controllerruntime.Request) error) *MockServiceGLBUseCase_EnsureServiceGLBUseCase_Call {
	_c.Call.Return(run)
	return _c
}

// InitServiceGLBUseCase provides a mock function for the type MockServiceGLBUseCase
func (_mock *MockServiceGLBUseCase) InitServiceGLBUseCase(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for InitServiceGLBUseCase")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockServiceGLBUseCase_InitServiceGLBUseCase_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InitServiceGLBUseCase'
type MockServiceGLBUseCase_InitServiceGLBUseCase_Call struct {
	*mock.Call
}

// InitServiceGLBUseCase is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockServiceGLBUseCase_Expecter) InitServiceGLBUseCase(ctx interface{}) *MockServiceGLBUseCase_InitServiceGLBUseCase_Call {
	return &MockServiceGLBUseCase_InitServiceGLBUseCase_Call{Call: _e.mock.On("InitServiceGLBUseCase", ctx)}
}

func (_c *MockServiceGLBUseCase_InitServiceGLBUseCase_Call) Run(run func(ctx context.Context)) *MockServiceGLBUseCase_InitServiceGLBUseCase_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockServiceGLBUseCase_InitServiceGLBUseCase_Call) Return(err error) *MockServiceGLBUseCase_InitServiceGLBUseCase_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockServiceGLBUseCase_InitServiceGLBUseCase_Call) RunAndReturn(run func(ctx context.Context) error) *MockServiceGLBUseCase_InitServiceGLBUseCase_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockALBGatewayUseCase creates a new instance of MockALBGatewayUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockALBGatewayUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockALBGatewayUseCase {
	mock := &MockALBGatewayUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockALBGatewayUseCase is an autogenerated mock type for the ALBGatewayUseCase type
type MockALBGatewayUseCase struct {
	mock.Mock
}

type MockALBGatewayUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockALBGatewayUseCase) EXPECT() *MockALBGatewayUseCase_Expecter {
	return &MockALBGatewayUseCase_Expecter{mock: &_m.Mock}
}

// DeleteALBGatewayUseCase provides a mock function for the type MockALBGatewayUseCase
func (_mock *MockALBGatewayUseCase) DeleteALBGatewayUseCase(ctx context.Context, req controllerruntime.Request) error {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for DeleteALBGatewayUseCase")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, controllerruntime.Request) error); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockALBGatewayUseCase_DeleteALBGatewayUseCase_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteALBGatewayUseCase'
type MockALBGatewayUseCase_DeleteALBGatewayUseCase_Call struct {
	*mock.Call
}

// DeleteALBGatewayUseCase is a helper method to define mock.On call
//   - ctx context.Context
//   - req controllerruntime.Request
func (_e *MockALBGatewayUseCase_Expecter) DeleteALBGatewayUseCase(ctx interface{}, req interface{}) *MockALBGatewayUseCase_DeleteALBGatewayUseCase_Call {
	return &MockALBGatewayUseCase_DeleteALBGatewayUseCase_Call{Call: _e.mock.On("DeleteALBGatewayUseCase", ctx, req)}
}

func (_c *MockALBGatewayUseCase_DeleteALBGatewayUseCase_Call) Run(run func(ctx context.Context, req controllerruntime.Request)) *MockALBGatewayUseCase_DeleteALBGatewayUseCase_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 controllerruntime.Request
		if args[1] != nil {
			arg1 = args[1].(controllerruntime.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockALBGatewayUseCase_DeleteALBGatewayUseCase_Call) Return(err error) *MockALBGatewayUseCase_DeleteALBGatewayUseCase_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockALBGatewayUseCase_DeleteALBGatewayUseCase_Call) RunAndReturn(run func(ctx context.Context, req controllerruntime.Request) error) *MockALBGatewayUseCase_DeleteALBGatewayUseCase_Call {
	_c.Call.Return(run)
	return _c
}

// EnqueueParentGatewayForRoute provides a mock function for the type MockALBGatewayUseCase
func (_mock *MockALBGatewayUseCase) EnqueueParentGatewayForRoute(ctx context.Context, routeRef controllerruntime.Request) error {
	ret := _mock.Called(ctx, routeRef)

	if len(ret) == 0 {
		panic("no return value specified for EnqueueParentGatewayForRoute")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, controllerruntime.Request) error); ok {
		r0 = returnFunc(ctx, routeRef)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockALBGatewayUseCase_EnqueueParentGatewayForRoute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnqueueParentGatewayForRoute'
type MockALBGatewayUseCase_EnqueueParentGatewayForRoute_Call struct {
	*mock.Call
}

// EnqueueParentGatewayForRoute is a helper method to define mock.On call
//   - ctx context.Context
//   - routeRef controllerruntime.Request
func (_e *MockALBGatewayUseCase_Expecter) EnqueueParentGatewayForRoute(ctx interface{}, routeRef interface{}) *MockALBGatewayUseCase_EnqueueParentGatewayForRoute_Call {
	return &MockALBGatewayUseCase_EnqueueParentGatewayForRoute_Call{Call: _e.mock.On("EnqueueParentGatewayForRoute", ctx, routeRef)}
}

func (_c *MockALBGatewayUseCase_EnqueueParentGatewayForRoute_Call) Run(run func(ctx context.Context, routeRef controllerruntime.Request)) *MockALBGatewayUseCase_EnqueueParentGatewayForRoute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 controllerruntime.Request
		if args[1] != nil {
			arg1 = args[1].(controllerruntime.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockALBGatewayUseCase_EnqueueParentGatewayForRoute_Call) Return(err error) *MockALBGatewayUseCase_EnqueueParentGatewayForRoute_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockALBGatewayUseCase_EnqueueParentGatewayForRoute_Call) RunAndReturn(run func(ctx context.Context, routeRef controllerruntime.Request) error) *MockALBGatewayUseCase_EnqueueParentGatewayForRoute_Call {
	_c.Call.Return(run)
	return _c
}

// EnsureALBGatewayUseCase provides a mock function for the type MockALBGatewayUseCase
func (_mock *MockALBGatewayUseCase) EnsureALBGatewayUseCase(ctx context.Context, req controllerruntime.Request) error {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for EnsureALBGatewayUseCase")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, controllerruntime.Request) error); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockALBGatewayUseCase_EnsureALBGatewayUseCase_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnsureALBGatewayUseCase'
type MockALBGatewayUseCase_EnsureALBGatewayUseCase_Call struct {
	*mock.Call
}

// EnsureALBGatewayUseCase is a helper method to define mock.On call
//   - ctx context.Context
//   - req controllerruntime.Request
func (_e *MockALBGatewayUseCase_Expecter) EnsureALBGatewayUseCase(ctx interface{}, req interface{}) *MockALBGatewayUseCase_EnsureALBGatewayUseCase_Call {
	return &MockALBGatewayUseCase_EnsureALBGatewayUseCase_Call{Call: _e.mock.On("EnsureALBGatewayUseCase", ctx, req)}
}

func (_c *MockALBGatewayUseCase_EnsureALBGatewayUseCase_Call) Run(run func(ctx context.Context, req controllerruntime.Request)) *MockALBGatewayUseCase_EnsureALBGatewayUseCase_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 controllerruntime.Request
		if args[1] != nil {
			arg1 = args[1].(controllerruntime.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockALBGatewayUseCase_EnsureALBGatewayUseCase_Call) Return(err error) *MockALBGatewayUseCase_EnsureALBGatewayUseCase_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockALBGatewayUseCase_EnsureALBGatewayUseCase_Call) RunAndReturn(run func(ctx context.Context, req controllerruntime.Request) error) *MockALBGatewayUseCase_EnsureALBGatewayUseCase_Call {
	_c.Call.Return(run)
	return _c
}

// InitALBGatewayUseCase provides a mock function for the type MockALBGatewayUseCase
func (_mock *MockALBGatewayUseCase) InitALBGatewayUseCase(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for InitALBGatewayUseCase")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockALBGatewayUseCase_InitALBGatewayUseCase_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InitALBGatewayUseCase'
type MockALBGatewayUseCase_InitALBGatewayUseCase_Call struct {
	*mock.Call
}

// InitALBGatewayUseCase is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockALBGatewayUseCase_Expecter) InitALBGatewayUseCase(ctx interface{}) *MockALBGatewayUseCase_InitALBGatewayUseCase_Call {
	return &MockALBGatewayUseCase_InitALBGatewayUseCase_Call{Call: _e.mock.On("InitALBGatewayUseCase", ctx)}
}

func (_c *MockALBGatewayUseCase_InitALBGatewayUseCase_Call) Run(run func(ctx context.Context)) *MockALBGatewayUseCase_InitALBGatewayUseCase_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockALBGatewayUseCase_InitALBGatewayUseCase_Call) Return(err error) *MockALBGatewayUseCase_InitALBGatewayUseCase_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockALBGatewayUseCase_InitALBGatewayUseCase_Call) RunAndReturn(run func(ctx context.Context) error) *MockALBGatewayUseCase_InitALBGatewayUseCase_Call {
	_c.Call.Return(run)
	return _c
}
