apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vngcloud-load-balancer-controller.fullname" . }}-manager
  labels:
    control-plane: manager
  {{- include "vngcloud-load-balancer-controller.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.manager.replicas }}
  selector:
    matchLabels:
      control-plane: manager
    {{- include "vngcloud-load-balancer-controller.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        control-plane: manager
      {{- include "vngcloud-load-balancer-controller.selectorLabels" . | nindent 8 }}
      annotations:
        kubectl.kubernetes.io/default-container: manager
    spec:
      affinity: {{- toYaml .Values.manager.affinity | nindent 8 }}
      containers:
      - args: {{- toYaml .Values.manager.manager.args | nindent 8 }}
        - --disable-alb-gateway-controller={{ not .Values.gatewayApi.alb.enabled }}
        - --disable-nlb-gateway-controller={{ not .Values.gatewayApi.nlb.enabled }}
        command:
        - /manager
        env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.manager.manager.image.repository }}:{{ .Values.manager.manager.image.tag
          | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.manager.manager.imagePullPolicy }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources: {{- toYaml .Values.manager.manager.resources | nindent 10 }}
        securityContext: {{- toYaml .Values.manager.manager.containerSecurityContext |
          nindent 10 }}
        volumeMounts:
        - mountPath: /etc/vngcloud-load-balancer-controller
          name: secret
          readOnly: true
        - mountPath: /etc/hosts
          name: add-hosts
          readOnly: true
      nodeSelector: {{- toYaml .Values.manager.nodeSelector | nindent 8 }}
      priorityClassName: {{ .Values.manager.priorityClassName }}
      securityContext: {{- toYaml .Values.manager.podSecurityContext | nindent 8 }}
      serviceAccountName: {{ include "vngcloud-load-balancer-controller.serviceAccountName"
        . }}
      terminationGracePeriodSeconds: 10
      tolerations: {{- toYaml .Values.manager.tolerations | nindent 8 }}
      topologySpreadConstraints: {{- toYaml .Values.manager.topologySpreadConstraints |
        nindent 8 }}
      volumes:
      - name: secret
        secret:
          secretName: {{ include "vngcloud-load-balancer-controller.fullname" . }}-mysecret
      - hostPath:
          path: /etc/hosts
          type: ""
        name: add-hosts
