{{- if .Values.gatewayApi.alb.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: vngcloud-alb
spec:
  controllerName: gateway.vks.vngcloud.vn/alb
  description: "VNGCloud ALB - L7 Gateway-API class."
{{- end }}
