name: CI Dev

on: push

env:
  VERSION: v0.0.1
  CHART_VERSION: 0.0.1
  REPO: vcr.vngcloud.vn/60108-annd2-ingress

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[build]')
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Log in to the GHCR
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to the vCR
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          registry: vcr.vngcloud.vn
          username: ${{ secrets.VCR_USER }}
          password: ${{ secrets.VCR_PASSWORD }}

      - name: Set variables
        id: vars
        run: |
          branch_after_format=$(git rev-parse --abbrev-ref HEAD | sed 's/[^a-zA-Z0-9]/-/g')
          echo $branch_after_format
          echo "BRANCH_NAME=$branch_after_format" >> $GITHUB_ENV

          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo $calculatedSha
          echo "COMMIT_SHORT_SHA=$calculatedSha" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0
        with:
          context: .
          push: true
          build-args: |
            VERSION=${{ env.VERSION }}
            COMMIT=${{ env.COMMIT_SHORT_SHA }}
          # platforms: linux/amd64
          # outputs: type=registry
          tags: |
            ghcr.io/vngcloud/vngcloud-load-balancer-controller:${{ env.COMMIT_SHORT_SHA }}
            ${{ env.REPO }}/vngcloud-load-balancer-controller:${{ env.COMMIT_SHORT_SHA }}
            ${{ env.REPO }}/vngcloud-load-balancer-controller:${{ env.VERSION }}
            ${{ env.REPO }}/vngcloud-load-balancer-controller:${{ env.BRANCH_NAME }}
          # target: vngcloud-load-balancer-controller

      - name: Push charts
        run: |
          helm package ./charts/vngcloud-load-balancer-controller --version ${{ env.CHART_VERSION }} --app-version ${{ env.VERSION }}
          helm push ./*.tgz oci://${{ env.REPO }}/vks-helm-charts
